const $ = (s, el = document) => el.querySelector(s);
const $$ = (s, el = document) => [...el.querySelectorAll(s)];
$('#year').textContent = new Date().getFullYear();
$$('[data-open]').forEach(button => button.addEventListener('click', () => $('#' + button.dataset.open).showModal()));
$$('[data-close]').forEach(button => button.addEventListener('click', () => button.closest('dialog').close()));
$$('dialog').forEach(dialog => dialog.addEventListener('click', e => { if (e.target === dialog) dialog.close(); }));
$$('[data-form]').forEach(form => form.addEventListener('submit', e => {
  e.preventDefault(); const result = $('.form-result', form.parentElement); const data = new FormData(form);
  result.hidden = false; form.hidden = true;
  result.innerHTML = form.dataset.form === 'starter' ? `<strong>Thank you, ${data.get('name')}.</strong><br>${({ 'I have songs but no plan':'Start with an Artist Direction Session—bring three songs or voice notes and we’ll turn them into a simple roadmap.', 'I want to write with someone':'A co-writing inquiry is a great next move. We’ll learn what kind of creative room feels right.', 'I’m ready to release something':'Let’s begin with a Release Mapping Session so the project has a clear, realistic runway.', 'I’m not sure yet':'That’s completely welcome. An Artist Direction Session is designed for exactly this moment.' })[data.get('path')]}<br><br><em>In the connected version, this inquiry will safely create a CRM lead and send a confirmation email.</em>` : `<strong>We received your inquiry, ${data.get('name')}.</strong><br>We’ll review it with care and follow up before confirming any session. <em>(Demo only—nothing has been sent.)</em>`;
}));
const pages = {
  overview: () => $('#overview-template').innerHTML,
  artists: () => table('Artists', [['Riley Monroe','Artist development','Active','Aug 21'],['Jordan Lee','Release planning','Active','Aug 28'],['Marisol James','Co-writing','Active','Sep 04'],['Alex Kim','Artist development','Inquiry','—']]),
  projects: () => table('Projects', [['Familiar Skies EP','Riley Monroe','Production','On track'],['First Light','Jordan Lee','Release map','Needs review'],['Open Window','Marisol James','Songwriting','Splits pending'],['Unlabeled ideas','Alex Kim','Discovery','New']]),
  songs: () => table('Songs & split status', [['Open Window','Marisol James','2 / 3 confirmed','Review needed'],['Familiar Skies','Riley Monroe','3 / 3 confirmed','Ready'],['Soft Landing','Alex Kim','Draft','Not started']]),
  billing: () => table('Billing attention', [['INV-1042','Jordan Lee','$850.00','4 days overdue'],['INV-1047','Riley Monroe','$1,200.00','Sent'],['INV-1048','Marisol James','$650.00','Draft']]),
  inquiries: () => table('New inquiries', [['Samira Ortiz','Co-writing','32 min ago','New'],['Evan Brooks','I don’t know where to start','Yesterday','New'],['Mia Chen','Release planning','Aug 6','Reviewing']]),
  calendar: () => `<p class="integration-note">Calendar availability is shown as a demo. Connect Google Calendar and Microsoft 365 in Setup before publishing booking availability.</p>${table('Upcoming sessions', [['Today · 3:00 PM','Co-write: Alex + Teo','90 min','Confirmed'],['Aug 12 · 11:00 AM','Project check-in: Riley','45 min','Confirmed'],['Aug 14 · 2:00 PM','Release review: Marisol','60 min','Tentative']])}`,
  files: () => `<div class="empty"><h2>Your file library is ready when you are.</h2><p>Connect Cloudflare R2 to securely store artist and project files.</p><button class="button" data-view="settings">Go to setup →</button></div>`,
  settings: () => `<p class="integration-note"><strong>Safe setup:</strong> Services are deliberately disconnected. Selecting “Connect” will show the exact configuration required—never enter credentials into this demo.</p><div class="setup-list">${connection('▣','Stripe','Test-mode billing, invoices & payment links','STRIPE_SECRET_KEY, STRIPE_WEBHOOK_SECRET')}${connection('✉','Resend','Transactional email for inquiries and invoices','RESEND_API_KEY, EMAIL_FROM')}${connection('G','Google Calendar','Availability and booking conflicts','GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET')}${connection('◧','Microsoft 365 / Outlook','Unified availability and booking conflicts','MICROSOFT_CLIENT_ID, MICROSOFT_CLIENT_SECRET')}${connection('☁','Cloudflare R2','Private artist and project file storage','R2_ACCOUNT_ID, R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY, R2_BUCKET')}${connection('◎','OpenAI','Optional, approval-gated operations assistant','OPENAI_API_KEY')}</div>`
};
function table(title, rows) { return `<section class="table-panel"><div class="panel-heading"><div><p class="eyebrow">Love & Sunshine</p><h2>${title}</h2></div><button class="button button-small">+ Add</button></div><table><thead><tr><th>NAME</th><th>DETAIL</th><th>STATUS</th><th>NEXT</th></tr></thead><tbody>${rows.map(r=>`<tr>${r.map((v,i)=>`<td>${i>1?`<span class="tag ${v==='Active'||v==='Ready'||v==='Confirmed'?'green':''}">${v}</span>`:v}</td>`).join('')}</tr>`).join('')}</tbody></table></section>`; }
function connection(icon, name, description, vars) { return `<article class="connection"><span class="icon">${icon}</span><div><h3>${name}</h3><p>${description}</p></div><button data-connect="${name}" data-vars="${vars}">Connect</button></article>`; }
function render(view='overview') { $('#view-content').innerHTML = pages[view](); $('#view-title').textContent = view === 'overview' ? 'Good morning, Maya.' : view.replace(/\b\w/g, c => c.toUpperCase()); $$('.dashboard [data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view)); $$('.dashboard [data-view]').forEach(b=>b.onclick=()=>render(b.dataset.view)); $$('[data-connect]').forEach(b=>b.onclick=()=>alert(`${b.dataset.connect} is ready to connect.\n\nWhen you choose to enable it, create or sign in to the Love & Sunshine account directly with ${b.dataset.connect}, then add these values to .env.local (never chat or commit them):\n${b.dataset.vars.split(', ').join('\n')}\n\nNo credentials are requested or stored by this prototype.`)); }
$('#open-dashboard').onclick=()=>{ $('#admin').close(); $('#dashboard').hidden=false; document.body.style.overflow='hidden'; render(); };
$('#exit-dashboard').onclick=()=>{ $('#dashboard').hidden=true; document.body.style.overflow=''; };
